config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'home#top'
  get "home/about"
  resources :users, only: [:index, :show, :edit, :create, :update] 
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]  do
  resources :book_comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, length: { maximum: 200 }
  validates :body, presence: true
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates_uniqueness_of :user_id, scope: :book_id
  belongs_to :user
  belongs_to :book
  validates :user_id, presence: true  
  validates :book_id, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image
  validates :name,   length: { in: 2..20 }
  validates :name, uniqueness: true
  validates :introduction,    length: { maximum: 50  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?
 protect_from_forgery with: :null_session

 
 def after_sign_in_path_for(resource)
    user_path(current_user)
 end
 
 def after_sign_up_path_for(resource)
     user_path(current_user)
 end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
  def reset_session
   super
   @form_authenticity_token = nil
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book_comment = @book.book_comments.new(book_comment_params)
    @book_comment.user_id = current_user.id
    if @book_comment.save
      redirect_to book_path(@book)
    else
      @book_comments = BookComment.where(book_id: @book.id)
      @user = current_user
      render 'books/show'
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    book_comment = @book.book_comments.find(params[:id])
   if book_comment.user != current_user
    redirect_to book_path(@book)
   end
    book_comment.destroy
    redirect_to book_path(@book)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
  def show
   @book = Book.find(params[:id])
   @new = Book
   @user = User.find(@book.user_id)
   @book_comments = @book.book_comments
   @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
    @users = User.all
  end

  def create
    @book= Book.new(book_params)
    @book.user_id = current_user.id
   if @book.save
    redirect_to book_path(@book.id), notice: "You have created book successfully."
   else
    @books = Book.all
    render :index
   end
  end

  def edit
    @book = Book.find(params[:id])
   if current_user.id != @book.user.id
   redirect_to books_path
   end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def update
   @book = Book.find(params[:id])
   if @book.update(book_params)
    redirect_to book_path(@book.id), notice: "You have updated book successfully."
   else
    render :edit
   end
  end

   private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!
  def show
   @user = User.find(params[:id])
   @book = Book.new
  end
  
  def index
   @user = User.all
   @book = Book.new
  end
  
  def edit
    @user = User.find(params[:id])
   if current_user.id != @user.id
   redirect_to user_path(current_user.id)
   end
  end
  
  def update
    @user = User.find(params[:id])
   if
    @user.update(user_params)
    redirect_to user_path(@user.id), notice:"You have updated user successfully."
   else
    render :edit
   end
  end
  
   private

  def user_params
   params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
 <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= pluralize(@book.errors.count, "error") %> errors prohibited this obj from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <%= form_with model: @book, local:true do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body %>
    </div>
    <div class="form-group">
      <%= f.submit 'Update Book' %>
  </div>
  <% end %>
<%= link_to "Show", book_path(@book.id) %> |
<%= link_to "Back", "/books" %>
  </div>
</div>
</div>

app/views/books/index.html.erb
<div class="container">
    <% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= pluralize(@book.errors.count, "error") %> errors prohibited this obj from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
   <% end %>
  <div class="row">
<%= render 'users/list', user: current_user, book: @book %>
<div class="col-md-9 ">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user.id) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
          <% end %></td>
        <td><%= link_to "#{ book.title}", book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td><% if book.favorited_by?(current_user) %>
      <%= link_to book_favorites_path(book), method: :delete do %>
         ♥<%= book.favorites.count %> 
      <% end %>
    <% else %>
      <%= link_to book_favorites_path(book), method: :post do %>
        ♡<%= book.favorites.count %> 
      <% end %>
    <% end %></td>
    <td>コメント数<%= book.book_comments.count %></td>
    <% end %>
      </tr>
  </tbody>
</table>
<div></div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
<%= render 'users/list', user: @user, book: @new %>
<div class="col-md-9">
  		<h2>Book detail</h2>
  		<table class="table">
  		  <tbody>
  		  <tr>
  		    <td><%= link_to user_path(@user.id) do %>
          <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%><br>
          <% end %>
  		 <%= link_to "#{ @user.name}", user_path(@user.id) %></td>
          <td><%= link_to  @book.title, @book %></td>
          <td><%= @book.body %></td>
  <td><% if @book.favorited_by?(current_user) %>
      <%= link_to book_favorites_path(@book), method: :delete do %>
         ♥<%= @book.favorites.count %> いいね
      <% end %>
    <% else %>
      <%= link_to book_favorites_path(@book), method: :post do %>
        ♡<%= @book.favorites.count %> いいね
      <% end %>
    <% end %>
          <td>コメント数：<%= @book.book_comments.count %></td>
          <td></td>
         <% if @book.user_id == current_user.id %>
          <td><%= link_to "Edit",  edit_book_path(@book.id) %></td>
          <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？" %></td>
         <% end %>
        </tr>
        <% @book_comments.each do |book_comment| %>
      <tr>
      <td><%= book_comment.comment %></td>
      　　<% if book_comment.user_id == current_user.id %>
      <td><%= link_to " コメントを消す", book_book_comment_path(@book,book_comment), method: :delete %></td>
     </tr><% end %>
        <% end %>
      </tbody></table><br>
         <% if @book_comment.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= pluralize(@book.errors.count, "error") %> errors prohibited this obj from being saved:</h2>
    <ul>
      <% @book_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
   <% end %>
      <div class="new-comment">
<%= form_with(model:[@book, @book_comment], local: true) do |f| %>
  <%= f.text_area :comment %>
  <%= f.submit "Create Book comment" %>
<% end %>
    </div>
  </div>

</div>
  <div></div>

app/views/home/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/home/top.html.erb
    <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          
        </div>
        <div class="row">
          
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
     </div>
   </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  </head>

  <body>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <p>Bookers</p>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse show" id="navbarNavDropdown" style="">
        <ul class="navbar-nav ml-auto">
     <% if user_signed_in? %>
          <li><i class="fas fa-home"></i><%= link_to "Home",   user_path(current_user.id) %></li>
          <li><i class="fas fa-users"></i><%= link_to "Users",  users_path %></li>
          <li><i class="fas fa-book-open"></i><%= link_to "Books",  books_path %></li>
          <li><i class="fas fa-sign-out-alt"></i><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
     <% else %>
          <li><i class="fas fa-home"></i><%= link_to "Home",   root_path %></li>
          <li><i class="fas fa-link"></i><%= link_to "About", home_about_path %></li>
          <li><i class="fas fa-user-plus"></i><%= link_to "sign up", new_user_registration_path %></li>
          <li><i class="fas fa-sign-in-alt"></i><%= link_to "login", new_user_session_path %> </li>
     <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
<br><br>
<main>
  <%= notice %>
  <%= yield %>
</main>
<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
  </body>
</html>

app/views/users/_list.html.erb
 <div class="col-md-3 ">
     <h2>User info</h2>
      
      <table class="table">
  <tbody>
  <tr>
	  <th><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></th>
  </tr>
  <tr>
	  <th>name <%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction <%= user.introduction %></th>
  </tr>
</tbody></table>
　
  <%= link_to edit_user_path(user.id), method: :get do %>
<i class="fas fa-user-cog"></i>
  <% end %>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: book, local:true do |f| %>
    <label for="book_title">Title
    <%= f.text_field :title %></label>
    <label for="book_opinion">Opinion
    <%= f.text_area :body %></label>
    <%= f.submit 'Create Book' %>
     <% end %>
</div>
    

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> errors prohibited this obj from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
   <% end %>
      <%= form_for(@user) do |f| %>
      <label><%= f.label :name %>
      <%= f.text_field :name %></label>
      <label><%= f.label :profile_image_id %>
      <%= f.attachment_field :profile_image %></label>
      <label><%= f.label :introduction %>
      <%= f.text_field :introduction %></label><br>
      <label><%= f.submit 'Update User' %></label>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
<%= render 'users/list', user: current_user, book: @book %>
<div class="col-md-9">
      <h2>Users</h2>
      <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @user.each do |user| %>
     <tr>
          <%= link_to user_path(user.id) do %>
      <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></td>
          <% end %>
      <td><%= user.name %></td>
      <td><%= link_to "Show", user_path(user.id) %></td>
     </tr>
    <% end %>
  </tbody>
</table> 
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
 <div class="row">
<%= render 'users/list', user: @user, book: @book %>
   <div class="col-md-9 ">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
         <% @user.books.each do |book| %>
         <tr>
          <td><%= link_to user_path(@user.id) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></td>
          　 <% end %>
          <td><%= link_to "#{book.title}",book_path(book.id) %></td>
          <td><%= book.body %></td>
          <td>コメント数<%= book.book_comments.count %></td>
        <% end %>
        </tr>
         </tbody>
      </table>
        </div>
       </div>
      </div>